import type { PilotEvent } from "../types/events.js";
import type { TaskRecord } from "../types/state.js";
import type { RepoConfig } from "../types/config.js";
import type { GitHubClient } from "../poller/github-client.js";
import type { ClaudeCliRunner } from "../claude/cli-runner.js";
import type { TaskRepository } from "../state/task-repository.js";
import type { GitOperations } from "../git/git-operations.js";

export class CodeExecutor {
  constructor(
    private github: GitHubClient,
    private claude: ClaudeCliRunner,
    private taskRepo: TaskRepository,
    private git: GitOperations,
    private repoConfig: RepoConfig
  ) {}

  async execute(event: PilotEvent, task: TaskRecord): Promise<void> {
    const { issue_number: issueNumber } = event;
    const branchName = `claude-pilot/issue-${issueNumber}`;

    try {
      // 1. Create branch from base
      console.log(
        `[CodeExecutor] Creating branch '${branchName}' from '${this.repoConfig.base_branch}'`
      );
      await this.git.createBranch(branchName, this.repoConfig.base_branch);

      // 2. Record branch name in task
      this.taskRepo.updateBranch(task.id, branchName);

      // 3. Fetch issue details
      console.log(`[CodeExecutor] Fetching issue #${issueNumber}`);
      const issue = await this.github.getIssue(issueNumber);

      // 4. Build execution prompt
      const prompt = [
        `You are implementing a GitHub issue. Follow all project conventions defined in CLAUDE.md.`,
        ``,
        `## Issue #${issueNumber}: ${issue.title}`,
        ``,
        issue.body ?? "(no description provided)",
        ``,
        `## Instructions`,
        `- Implement the changes described in the issue above.`,
        `- Follow the project's CLAUDE.md conventions exactly.`,
        `- Create git commits for your changes with clear, descriptive commit messages.`,
        `- Do NOT push — pushing will be handled separately.`,
      ].join("\n");

      // 5. Run Claude to implement changes
      console.log(
        `[CodeExecutor] Running Claude CLI to implement issue #${issueNumber}`
      );
      await this.claude.runExecute(prompt, this.repoConfig.local_path);

      // 6. Commit any remaining uncommitted changes
      const hasUncommitted = await this.git.hasChanges();
      if (hasUncommitted) {
        console.log(
          `[CodeExecutor] Committing uncommitted changes for issue #${issueNumber}`
        );
        await this.git.commitAll(`feat: implement issue #${issueNumber}`);
      }

      // 7. Push branch to remote
      console.log(`[CodeExecutor] Pushing branch '${branchName}'`);
      await this.git.push(branchName);

      // 8. Create pull request
      const rawTitle = issue.title ?? `Issue #${issueNumber}`;
      const prTitle =
        rawTitle.length > 70 ? rawTitle.slice(0, 70) : rawTitle;

      const prBody = [
        `Closes #${issueNumber}`,
        ``,
        `This PR was automatically generated by claude-pilot based on the issue description.`,
        ``,
        `<!-- claude-pilot -->`,
      ].join("\n");

      console.log(
        `[CodeExecutor] Creating pull request for issue #${issueNumber}`
      );
      const prNumber = await this.github.createPullRequest(
        branchName,
        this.repoConfig.base_branch,
        prTitle,
        prBody
      );

      // 9. Update task state
      this.taskRepo.updatePrNumber(task.id, prNumber);
      this.taskRepo.updateStatus(task.id, "PR_CREATED");

      // 10. Post success comment on the issue
      const prUrl = `https://github.com/${this.repoConfig.name}/pull/${prNumber}`;
      const successComment = [
        `✅ PR #${prNumber} created: ${prUrl}`,
        ``,
        `<!-- claude-pilot -->`,
      ].join("\n");

      console.log(
        `[CodeExecutor] Posting success comment on issue #${issueNumber}`
      );
      await this.github.createIssueComment(issueNumber, successComment);

      console.log(
        `[CodeExecutor] Done — issue #${issueNumber} -> PR #${prNumber} (${prUrl})`
      );
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      console.log(
        `[CodeExecutor] Error processing issue #${issueNumber}: ${message}`
      );

      const errorComment = [
        `❌ Failed to create PR for issue #${issueNumber}.`,
        ``,
        `**Error:**`,
        `\`\`\``,
        message,
        `\`\`\``,
        ``,
        `<!-- claude-pilot -->`,
      ].join("\n");

      try {
        await this.github.createIssueComment(issueNumber, errorComment);
      } catch (commentErr: unknown) {
        const commentMsg =
          commentErr instanceof Error ? commentErr.message : String(commentErr);
        console.log(
          `[CodeExecutor] Failed to post error comment on issue #${issueNumber}: ${commentMsg}`
        );
      }

      throw err;
    }
  }
}
